name: spring-todo
services:
  api:
    container_name: Spring-Todo-Api
    build:
      context: backend
      target: development
    ports:
      - 8080:8080
    networks:
      - network
    develop:
      watch:
        - action: rebuild
          path: ./backend
    env_file:
      - path: ./.env
        required: true

  web:
    container_name: Spring-Todo-Web
    build:
      context: frontend
    ports:
      - 8081:8081
    volumes:
      - ./frontend:/usr/app/frontend
      # Anonymous volume to prevent overwriting container node_modules when mounted
      - /usr/app/frontend/node_modules
    networks:
      - network
    depends_on:
      - api

# Enabled by default, just setting it here for naming purposes
networks:
  network:
    driver: bridge