spring:
  application:
    name: todoapp
  datasource:
    url: jdbc:h2:mem:mydb
  jpa:
    defer-datasource-initialization: true
  h2:
    # http://localhost:8080/h2-console
    enabled: true

server:
  error:
    include-stacktrace: never

management:
  endpoint:
    health:
      # Default just displays "UP" if all is good
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info
  # Required to allow /actuator/info to work
  #   - see https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.6-Release-Notes#actuator-env-infocontributor-disabled-by-default
  info:
    env:
      enabled: true

# displayed via /actuator/info endpoint
info:
  links:
    repo: TESTING_DEV
    discord: AYY_LMAO


---
spring:
  config:
    activate:
      on-profile: "prod"
  h2:
    enabled: false

info:
  links:
    repo: https://github.com/rezbee-dev/Spring-Fullstack-Todo
    discord: https://discord.gg/Udhs323Wtm